In [1]:
!pip install torchaudio

  Using cached torch-1.10.0-cp38-none-macosx_10_9_x86_64.whl (147.1 MB)
  Attempting uninstall: torch
    Found existing installation: torch 1.11.0
    Uninstalling torch-1.11.0:
      Successfully uninstalled torch-1.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.12.0 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.


In [2]:
from torchaudio import datasets

In [ ]:
datasets.VCTK_092('data/', download = True)

In [15]:
import torch
y = torch.arange(25).view(5, 5)

In [20]:
gate, filter, q = torch.chunk(y, 3, dim=1)

In [21]:
gate 

tensor([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]])

In [22]:
filter

tensor([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]])

In [23]:
q

tensor([[ 4],
        [ 9],
        [14],
        [19],
        [24]])